### ISSUE TITLE
Can't build midori with bitbake

### ISSUE THREAD

**Issue by heylouiz** [open-switch/ops-build#1]
Hi, I'm having problems building the midori recipe (master/yocto/poky/meta/recipes-sato/midori/midori_0.5.8.bb)
It fails in the **FindVala.cmake**, I can't get the logfile now because i'm not at work, as soon as I get there tomorrow I can update this issue.
But can you confirm that "bitbake midori" is working?

Thanks!

**Comment by jeff-yin** [comment]
Closing issue as this repo is no longer being actively developed or supported.
